###POST
POST http://localhost:8080/actuator/shutdown

###로깅레벨 조회
GET http://localhost:8080/actuator/loggers/hello.controller


###로깅레벨 변경
POST http://localhost:8080/actuator/loggers/hello.controller
Content-Type: application/json

{
  "configuredLevel": "TRACE"
}